name: overwatch_region_control
description: "Choose server region you want play with."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/emoji/flag_tw.svg
    - assets/emoji/flag_jp.svg
    - assets/emoji/flag_kr.svg
    - assets/emoji/flag_sg.svg
    - assets/emoji/flag_eu.svg
    - assets/emoji/flag_us.svg
    - assets/emoji/flag_br.svg
    - assets/emoji/flag_au.svg
    - assets/emoji/earth_africa.svg
    - assets/emoji/globe_with_meridians.svg
